// Package docs Code generated by swaggo/swag. Run "swag init -g cmd/server/main.go" to regenerate.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
 "schemes": {{ marshal .Schemes }},
 "swagger": "2.0",
 "info": {
  "description": "{{escape .Description}}",
  "title": "{{.Title}}",
  "version": "{{.Version}}"
 },
 "host": "{{.Host}}",
 "basePath": "{{.BasePath}}",
 "paths": {
  "/eco-attributes": {
   "get": {
    "description": "Returns all eco attributes (use IDs when creating events)",
    "tags": ["eco-attributes"],
    "produces": ["application/json"],
    "summary": "List eco attributes",
    "responses": {
     "200": {
      "description": "OK",
      "schema": {
       "type": "array",
       "items": {
        "$ref": "#/definitions/models.EcoAttribute"
       }
      }
     }
    }
   }
  },
  "/events": {
   "post": {
    "description": "Creates an event and verifies Green criteria (eco venue + 2+ sustainability flags)",
    "tags": ["events"],
    "consumes": ["application/json"],
    "produces": ["application/json"],
    "summary": "Create a new event",
    "parameters": [
     {
      "description": "Event details",
      "name": "event",
      "in": "body",
      "required": true,
      "schema": {
       "$ref": "#/definitions/models.CreateEventRequest"
      }
     }
    ],
    "responses": {
     "201": {
      "description": "Created",
      "schema": {
       "$ref": "#/definitions/models.CreateEventResponse"
      }
     },
     "400": {"description": "Invalid request"},
     "404": {"description": "Venue not found"},
     "500": {"description": "Server error"}
    }
   }
  }
 },
 "definitions": {
  "models.CreateEventRequest": {
   "type": "object",
   "required": ["title", "description", "organizer_id", "event_date", "event_start_time", "event_end_time"],
   "properties": {
    "title": {"type": "string"},
    "description": {"type": "string"},
    "organizer_id": {"type": "string", "format": "uuid"},
    "venue_id": {"type": "string", "format": "uuid"},
    "event_date": {"type": "string"},
    "event_start_time": {"type": "string"},
    "event_end_time": {"type": "string"},
    "eco_summary": {"type": "string"},
    "ticket_price": {"type": "number"},
    "total_capacity": {"type": "integer"},
    "eco_attribute_ids": {
     "type": "array",
     "items": {"type": "string", "format": "uuid"}
    }
   }
  },
  "models.CreateEventResponse": {
   "type": "object",
   "properties": {
    "event": {"$ref": "#/definitions/models.Event"},
    "is_green": {"type": "boolean"},
    "green_criteria_met": {"type": "array", "items": {"type": "string"}},
    "green_criteria_not_met": {"type": "array", "items": {"type": "string"}}
   }
  },
  "models.EcoAttribute": {
   "type": "object",
   "properties": {
    "id": {"type": "string", "format": "uuid"},
    "name": {"type": "string"},
    "category": {"type": "string"}
   }
  },
  "models.Event": {
   "type": "object",
   "properties": {
    "id": {"type": "string", "format": "uuid"},
    "title": {"type": "string"},
    "description": {"type": "string"},
    "is_eco_friendly": {"type": "boolean"},
    "ticket_price": {"type": "number"},
    "total_capacity": {"type": "integer"}
   }
  }
 }
}`

var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "EventLeaf API",
	Description:      "Eco-focused event management API with Green criteria verification",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
